project:
  type: website
  resources:
    - awesomestyle.css
    - js/vdrSignalAnalysis.js
    - calculatrices/malibrairie.js

website:
  title: "Carnet de Nicolas"
  favicon: img/favicon/favicon.png
  site-url: https://respiratoire.ca/
  open-graph: true
  search:
    show-item-context: true
    keyboard-shortcut: ["?"]
  sidebar:
    - id: "calculatrices"
      title: "Calculatrices"
      style: "floating"
      contents:
        - section: Calculatrices
          contents: "calculatrices/*.qmd"
  navbar:
    background: primary
    title: false
    logo: img/logo/NÃ©buliseur2-simple.svg
    left:
      - icon: newspaper
        href: index.qmd
      - icon: flask
        href: projets.qmd
      - icon: projector
        href: presentations.qmd
      - icon: calculator
        href: calculatrices/index.qmd
    tools:
      - icon: rss
        title: Flux RSS
        href: index.xml

format:
  html:
    html-math-method: mathml
    lang: fr
    theme: flatly
    css: awesomestyle.css
