project:
  type: website
  resources:
    - awesomestyle.css
    - js/vdrSignalAnalysis.js

website:
  title: "Carnet de Nicolas"
  favicon: img/favicon/favicon.png
#  site-url: https://progrt.github.io/
  site-url: https://respiratoire.ca/
  open-graph: true
  navbar:
    background: primary
    title: false
    logo: img/logo/NÃ©buliseur2-simple.svg
    left:
      - index.qmd
      - projets.qmd
      - presentations.qmd
      - text: Calculatrices
        href: https://observablehq.com/collection/@progrt/calculatrices-respiratoires
    tools:
      - icon: rss
        title: Flux RSS
        href: index.xml

format:
  html:
    html-math-method: mathml
    lang: fr
    theme: flatly
    css: awesomestyle.css
